### ISSUE TITLE
How to Delete wfdb Completely in a Directory?

### ISSUE THREAD

**Issue by sami10007** [ikarosilva/wfdb-app-toolbox#124] opened 2016-04-28 15:18 UTC
There is a common misunderstanding about how to uninstall wfdb because many users cannot restore the system, for instance the ticket #123 about OS X. Observation is that if the wfdb system breaks (etc just initiate function with wrong parameters), you cannot use the folder again where the system was initiated. I want to delete the effects of the following commands
```
[old_path]=which('rdsamp');if(~isempty(old_path)) rmpath(old_path(1:end-8)); end
wfdb_url='https://github.com/ikarosilva/wfdb-app-toolbox/raw/master/wfdb-app-toolbox-0-9-10.zip';
[filestr,status] = urlwrite(wfdb_url,'wfdb-app-toolbox-0-9-10.zip');%Octave users may have to download manually
unzip('wfdb-app-toolbox-0-9-10.zip');
cd mcode
addpath(pwd);savepath
```

My attempts

- delete `mcode` directory, however, unsuccessful result
- ...

**Hypothesis**: the initiating commands may be the source of the problem in OS X.
I extended the problem to StackOverflow thread [Can wfdb Matlab commands differ in Linux and OS X?](http://stackoverflow.com/q/36919082/54964) because I do not understand myself the interaction of OS X with the commands. 

---

How can you Delete wfdb Completely in a Directory?

**Comment by ikarosilva** [comment] 2016-04-28 16:37
Duplicate of #121

**Closed by ikarosilva** 2016-04-28 16:37 UTC
