### ISSUE TITLE
Diff [~,config] vs [isloaded,config] from wfdbloadlib(...)?

### ISSUE THREAD

**Issue by sami10007** [ikarosilva/wfdb-app-toolbox#122] opened 2016-04-27 14:34 UTC
System: OS X 10.11.4, WFDB 0-9-10. 

**Command 1**
```
[~,config]=wfdbloadlib(debugLevel, networkWaitTime);
```

which sometimes gives output
```
Apr 27, 2016 5:22:30 PM org.physionet.wfdb.Wfdbexec gen_exec_arguments
FINEST: 
	***commandInput.add = /Users/masi/myCode/nativelibs/macosx/bin/wfdb-config
Apr 27, 2016 5:22:30 PM org.physionet.wfdb.Wfdbexec setLauncher

...
```
Running many times solves the issue. Parameter `config` struct of configuration parameters. 
I am not sure what where `~` refers to, but it does not seem to boolean like in Command 2, and not home directory. **Command 2**
```
[isloaded,config]=wfdbloadlib(debugLevel, networkWaitTime);
```
No such behaviour (weak evidence, since few trials). Expected behaviour `isloaded` boolean. Parameter `config` struct of configuration parameters. 

# Complications

I get similar outputs then in many other environments, for instance the following
```
[sig, Fs, tm1]=rdsamp(strcat('mitdb/',num2str(patient)),channel,N0,rawUnits); 
```
Output
```
Apr 27, 2016 5:35:20 PM org.physionet.wfdb.Wfdbexec <init>
FINEST: 
	***Setting exec commandName to: /Users/masi/code/mcode/nativelibs/macosx/bin/rdsamp
Apr 27, 2016 5:35:20 PM org.physionet.wfdb.Wfdbexec setWFDB_PATH
FINEST: 

....
```
I think this complication can be a sign of a general problem. 

---

What is the difference between `[~,config]` vs `[isloaded,config]` from `wfdbloadlib(...)`?

**Comment by ikarosilva** [comment] 2016-04-28 12:37
Hi  [~,config]=wfdbloadlib(debugLevel, networkWaitTime);

The ~ is a dummy variable that MATLAB uses to to discard unwanted outputs in functions returning multiple outputs (similar to "_" in Python.

-Ikaro 

 

    On Wednesday, April 27, 2016 10:34 AM, Sami L. <notifications@github.com> wrote:
 

 Command 1[~,config]=wfdbloadlib(debugLevel, networkWaitTime);
which sometimes give outputApr 27, 2016 5:22:30 PM org.physionet.wfdb.Wfdbexec gen_exec_arguments
FINEST: 
    ***commandInput.add = /Users/masi/myCode/nativelibs/macosx/bin/wfdb-config
Apr 27, 2016 5:22:30 PM org.physionet.wfdb.Wfdbexec setLauncher

...
Running many times solves the issue. Parameter config struct of configuration parameters. 
I am not sure what where ~ refers to, but it does not seem to boolean like in Command 2, and not home directory. Command 2[isloaded,config]=wfdbloadlib(debugLevel, networkWaitTime);
No such behaviour (weak evidence, since few trials). Expected behaviour isloaded boolean. Parameter config struct of configuration parameters. What is the difference between [~,config] vs [isloaded,config] from wfdbloadlib(...)?—

**Comment by sami10007** [comment] 2016-04-28 13:12
Yes, that I thought. 

I can now reproduce the error messages with `[isloaded,config]`. Complete error message

```
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec gen_exec_arguments
FINEST: 
	***commandInput.add = /Users/masi/myCode/mcode/nativelibs/macosx/bin/wfdb-config
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec setLauncher
FINER: 
	***setting: DYLD_LIBRARY_PATH: /Users/masi/myCode/mcode/nativelibs/macosx/bin:/Users/masi/myCode/mcode/nativelibs/macosx/lib64:/Users/masi/myCode/mcode/nativelibs/macosx/lib:/Applications/MATLAB_R2016a.app/sys/os/maci64:/Applications/MATLAB_R2016a.app/bin/maci64/../../Contents/MacOS:/Applications/MATLAB_R2016a.app/bin/maci64:/Applications/MATLAB_R2016a.app/extern/lib/maci64:/Applications/MATLAB_R2016a.app/runtime/maci64:/Applications/MATLAB_R2016a.app/sys/java/jre/maci64/jre/lib/./native_threads:/Applications/MATLAB_R2016a.app/sys/java/jre/maci64/jre/lib/./server:/Applications/MATLAB_R2016a.app/sys/java/jre/maci64/jre/lib/./lib/jli
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec setLauncher
FINER: 
	***setting: MacOs PATH: /Users/masi/myCode/mcode/nativelibs/macosx/bin:/Users/masi/myCode/mcode/nativelibs/macosx/lib64:/Users/masi/myCode/mcode/nativelibs/macosx/lib:/Applications/MATLAB_R2016a.app/sys/os/maci64:/Applications/MATLAB_R2016a.app/bin/maci64/../../Contents/MacOS:/Applications/MATLAB_R2016a.app/bin/maci64:/Applications/MATLAB_R2016a.app/extern/lib/maci64:/Applications/MATLAB_R2016a.app/runtime/maci64:/Applications/MATLAB_R2016a.app/sys/java/jre/maci64/jre/lib/./native_threads:/Applications/MATLAB_R2016a.app/sys/java/jre/maci64/jre/lib/./server:/Applications/MATLAB_R2016a.app/sys/java/jre/maci64/jre/lib/./lib/jli
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec setLauncher
FINEST: 
	***Setting executing process with command and arguments: [/Users/masi/myCode/mcode/nativelibs/macosx/bin/wfdb-config, --version]
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec execToStringList
FINE: 
	***Executing Launcher with commandInput : 	[/Users/masi/myCode/mcode/nativelibs/macosx/bin/wfdb-config, --version]
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec execToStringList
FINER: 
	***Starting exec process...
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec execToStringList
FINER: 
	***Creating read buffer and waiting for exec process...
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec execToStringList
FINEST: 
	***Waiting for data stream from launcher...
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec execToStringList
FINEST: 
	***A was stream initialized, checking if data or err...
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec execToStringList
FINEST: 
	***Reading output: 
10.5.24
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec getEnvironment
FINER: 
	***WFDB_JAVA_HOME: /Users/masi/myCode/mcode/
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec getEnvironment
FINER: 
	***WFDB_NATIVE_BIN: /Users/masi/myCode/mcode/nativelibs/macosx/
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec getEnvironment
FINER: 
	***Exec dir: null
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec getEnvironment
FINER: 
	***OS: macosx
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec getEnvironment
FINER: 
	***fullOsName: Mac OS X
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec getEnvironment
FINER: 
	***OS Arch: x86_64
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec getEnvironment
FINER: 
	***customArchFlag: false
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec getEnvironment
FINER: 
	***OS Version: 10.11.4
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec getEnvironment
FINER: 
	***JVM Version: 1.7.0_75
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec <init>
FINEST: 
	***Setting exec commandName to: /Users/masi/myCode/mcode/nativelibs/macosx/bin/rdsamp
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec setWFDB_PATH
FINEST: 
	***Setting WFDB to: . /Users/masi/myCode/mcode/../database/ http://physionet.org/physiobank/database/
Apr 28, 2016 4:09:01 PM org.physionet.wfdb.Wfdbexec setWFDBCAL
FINEST: 
	***Setting WFDBCAL to:  /Users/masi/myCode/mcode//database/wfdbcal
Error using javaObject
No class org.physionet.wfdb.jni.Rdsamp can be located on the Java class path

Error in rdsamp (line 114)
    javaWfdbRdsamp=javaObject('org.physionet.wfdb.jni.Rdsamp');

Error in make_bj_1s (line 80)
[sig, Fs, tm1]=rdsamp(strcat('mitdb/',num2str(patient)),channel,N0,rawUnits); % plot(tm,sig);
```

**Comment by ikarosilva** [comment] 2016-04-28 16:39
Duplicate of #121

**Closed by ikarosilva** 2016-04-28 16:39 UTC
