### ISSUE TITLE
rdann outputs incorrect annotations if only one output requested

### ISSUE THREAD

**Issue by alistairewj** [ikarosilva/wfdb-app-toolbox#132] opened 2016-10-28 14:56 UTC
Thanks to @mansirankawat for noticing this. Reproducible using `slp01a.ecg` and `slp01a.hea` at https://www.physionet.org/physiobank/database/slpdb/

If all outputs of `rdann` are requested, then the output looks correct:

``` matlab
[ann,type,subtype,chan,num,comments]=rdann('slp01a', 'ecg');
ann(1:5)
```

```
ans =

    20
   235
   458
   688
   912
```

But if only a single output is requested, then the annotations all return 50:

``` matlab
ann=rdann('slp01a', 'ecg');
ann(1:5)
```

```
ans =

    50
    50
    50
    50
    50
```

Verified using the wfdb-app-toolbox-0-9-9 release on Ubuntu 16.04.

**Comment by cx1111** [comment] 2016-10-31 18:47
The inconsistency is produced by the output of line 172:
`ann=javaWfdbExec.execToDoubleArray(wfdb_argument); `

I did notice that this `ann` array is Nx5 for records with headers without a time/date, and Nx6 for those with a time/date like this problem record.

I'm just reasoning here without delving into the results of the java class but my simple change seems to have fixed the error. Do you think I should close this issue?

**Comment by mansirankawat** [comment] 2016-11-01 07:24
Thanks @cx1111 for looking into this issue. It works for the following case now
ann = rdann('slp01a', 'ecg') 
But, for the following case
[ann_atr]=rdann('slp01a', 'ecg', 1, 1650000, 1500001);

It gives me 
error: [java] java.lang.NullPointerException
error: called from:
error:   /home/user/Desktop/entry_sleep/entry_87.53_best_correct/wfdb-app-toolbox-0-9-9/mcode/rdann.m at line 172, column 4

Although, there are annotations beyond 1650000

**Comment by cx1111** [comment] 2016-11-01 12:50
I'm using the latest github development version of everything. I copied your command in exactly and got a 668x1 double for ann_atr.  Can you try with the most up to date version of the toolbox and tell me what you get?

**Comment by cx1111** [comment] 2016-11-01 14:35
Either way I found another error when reading annotation files with aux fields (when the number of outputs is 1).

```
 Error using rdann (line 173)
 Java exception occurred:
 java.lang.ArrayIndexOutOfBoundsException: 8
 	at org.physionet.wfdb.Wfdbexec.execToDoubleArray(Unknown Source)
```
So unfortunately the problem is within the java code. I'll be investigating.

**Comment by sami10007** [comment] 2016-11-01 15:26
@cx1111 Can you please describe how you exactly set up the WFDB system from bottom to the up? I.e. from downloading the tarball to the test function found here, for instance. It seems that there may be some inconsistencies which may be causing the problem. I really want to understand it as soon as possible.

**Comment by cx1111** [comment] 2016-11-01 15:40
I'm not using a tarball/release version but rather the latest development version on github. I git clone the repo, then in matlab:

```
[old_path]=which('rdsamp');if(~isempty(old_path)) rmpath(old_path(1:end-8)); end
cd mcode
addpath(pwd);savepath
```

**Comment by sami10007** [comment] 2016-11-01 15:43
@cx1111 Can you please add the complete work flow until the test command? I want to get a confirmation that there is nothing wrong in my installation of WFDB.

**Comment by cx1111** [comment] 2016-11-01 15:50
In terminal: 

```
cd ~/Testfolder/
~/Testfolder$ git clone https://github.com/ikarosilva/wfdb-app-toolbox.git
matlab &
```
In matlab:

```
[old_path]=which('rdsamp');if(~isempty(old_path)) rmpath(old_path(1:end-8)); end
cd wfdb-app-toolbox/mcode
addpath(pwd);savepath
```

**Comment by sami10007** [comment] 2016-11-01 16:00
Can you now simply run `tic; sig=rdsamp('16265'); toc;` if you have manually downloaded the file to your working directory?

**Comment by cx1111** [comment] 2016-11-01 17:28
```
>> tic; sig=rdsamp('16265'); toc;
Elapsed time is 1.488436 seconds.
```

**Comment by mansirankawat** [comment] 2016-11-01 20:32
Thanks @cx1111, I also spotted that error in rdann. Also, when using wrann in matlab/octave for this slpdb dataset, I get the following error. 

[ann_atr]=rdann('slp01a', 'ecg')
wrann('slp01a', 'ecg1', ann_atr)


java.io.IOException: Broken pipe
    at java.io.FileOutputStream.writeBytes(Native Method)
    at java.io.FileOutputStream.write(FileOutputStream.java:318)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
    at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
    at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
    at java.io.BufferedWriter.write(BufferedWriter.java:230)
    at java.io.Writer.write(Writer.java:157)
    at org.physionet.wfdb.InputWriter.run(Unknown Source)
Process exited with errors!! Error code = 139
warning: broken pipe -- some output may be lost

Maybe they are related

**Comment by sami10007** [comment] 2016-11-06 17:57
@cx1111 Can you please provide the complete installation commands for a fresh system?

I started up 3rd PC with WFDB but your work flow is incomplete. What is the default way of handling warning with `pathdef.m`? 

I extended the case here: https://se.mathworks.com/matlabcentral/answers/310851-set-path-won-t-save-on-debian-8-5

**Comment by sami10007** [comment] 2016-11-08 14:50
This line is what I have used to overcome the pathdef.m issue with WFDB
`
addpath(fullfile(home, 'Documents/DI/', 'wfdb-app-toolbox', 'mcode'));
`
The output is unsuccessful

```
Error using rdsamp (line 203)
Could not find record: NSRDB/16272. Search path is set to: '.
/home/masi/Documents/DI/wfdb-app-toolbox/mcode/../database/ http://physionet.org/physiobank/database/'

Error in vertaa (line 165)
        [~, cSignals{cIndex}]=rdsamp(strcat(database,num2str(patient)),channel); % plot(tm,sig);
 
```

It has worked before but not now. Please, let me know how to solve the primary `pathdef.m` issue or the workaround.

**Comment by mansirankawat** [comment] 2016-11-19 19:24
@cx1111 Did you figure out why java code is causing problems for slpdb database?

**Comment by cx1111** [comment] 2016-11-22 22:53
Sorry I haven't had time to work on it but yea I found the error. I'll be editing the java method. In the meantime if you want you can delete that if(nargout==1) clause to make rdann work.

**Comment by cx1111** [comment] 2016-11-23 16:04
Ok hopefully I've fixed the issue. Changed Wfdbexec.java and Wfdbexec.class in the wfdb-app-JVM7-0-9-10.jar file, along with a bit in rdann.

**Closed** 2016-11-23 20:27 UTC
